# Generated by Django 3.2.8 on 2021-12-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
